package com.fag.sistema.domain.enums;

public enum EnumBeneficios {
  HORA_EXTRA,
  COMISSAO,
  SALARIO_MATERNIDADE,
  QUINQUENIO,
  ADICIONAL_NOTURNO,
  ADICIONAL_INSALUBRIDADE,
  ADICIONAL_PERICULOSIDADE,
  SALARIO_FAMILIA,
  AUXILIO_CRECHE,
  DIARIAS_VIAGEM;
}
